export const ROUTES = {
  LOGIN: '/login',
  CHANGE_PASSWORD: '/change-password',
  DASHBOARD: '/admin',
  POS: '/admin/pos',
  ORDERS: '/admin/orders',
  ORDER_DETAIL: (id) => `/admin/orders/${id}`,
  MENU: '/admin/menu',
  PUBLIC_MENU: '/menu',
  MENU_CATEGORY: (id) => `/admin/menu/category/${id}`,
  MENU_ITEM: (id) => `/admin/menu/item/${id}`,
  INVENTORY: '/admin/inventory',
  INVENTORY_ITEM: (id) => `/admin/inventory/${id}`,
  KDS: '/admin/kds',
  CUSTOMERS: '/admin/customers',
  CUSTOMER_DETAIL: (id) => `/admin/customers/${id}`,
  HR: '/admin/hr',
  HR_EMPLOYEE: (id) => `/admin/hr/${id}`,
  ACCOUNTING: '/admin/accounting',
  REPORTS: '/admin/reports',
  SETTINGS: '/admin/settings',
  PROFILE: '/admin/profile',
  TABLES: '/admin/tables',
  SUPPLIERS: '/admin/suppliers',
  RECIPES: '/admin/recipes',
  DELIVERY: '/admin/delivery',
  CRM: '/admin/crm',
};
